name: CI

on: workflow_dispatch

env:
  FOUNDRY_PROFILE: ci

jobs:
  test:
    strategy:
      fail-fast: true

    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Foundry | Install
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Forge | Build
        run: |
          forge --version
          forge build --sizes

      - name: Forge | Test
        run: |
          forge test -vvv
